/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.medico;

/**
 *
 * @author BrunoCardozzzo
 */
public class jfMedico extends javax.swing.JFrame {


    private medico objMed;
    
    public jfMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        idmedico = new javax.swing.JTextField();
        nomemedico = new javax.swing.JTextField();
        cpfmedico = new javax.swing.JTextField();
        idademedico = new javax.swing.JTextField();
        sexomedico = new javax.swing.JTextField();
        salariomedico = new javax.swing.JTextField();
        emailmedico = new javax.swing.JTextField();
        celularmedico = new javax.swing.JTextField();
        espmedico = new javax.swing.JTextField();
        rua = new javax.swing.JTextField();
        bairro = new javax.swing.JTextField();
        cep = new javax.swing.JTextField();
        unidade = new javax.swing.JTextField();
        novo = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setEnabled(false);

        jLabel1.setText("ID");

        jLabel2.setText("nome");

        jLabel3.setText("cpf");

        jLabel4.setText("idade");

        jLabel5.setText("sexo");

        jLabel6.setText("salario");

        jLabel7.setText("E-mail");

        jLabel8.setText("celular");

        jLabel9.setText("especialidade");

        jLabel10.setText("rua");

        jLabel11.setText("bairro");

        jLabel12.setText("cep");

        jLabel13.setText("unidade");

        idmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idmedicoActionPerformed(evt);
            }
        });

        nomemedico.setEnabled(false);

        cpfmedico.setEnabled(false);

        idademedico.setEnabled(false);

        sexomedico.setEnabled(false);

        salariomedico.setEnabled(false);

        emailmedico.setEnabled(false);
        emailmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailmedicoActionPerformed(evt);
            }
        });

        celularmedico.setEnabled(false);

        espmedico.setEnabled(false);

        rua.setEnabled(false);
        rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaActionPerformed(evt);
            }
        });

        bairro.setEnabled(false);

        cep.setEnabled(false);

        unidade.setEnabled(false);

        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        salvar.setText("Salvar");
        salvar.setEnabled(false);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        editar.setText("Editar");
        editar.setEnabled(false);

        excluir.setText("Excluir");
        excluir.setEnabled(false);

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        pesquisar.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(novo)
                        .addGap(18, 18, 18)
                        .addComponent(salvar)
                        .addGap(18, 18, 18)
                        .addComponent(editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(espmedico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(emailmedico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(celularmedico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cpfmedico)
                                            .addComponent(idmedico, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(idademedico, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)))
                                        .addGap(18, 18, 18)
                                        .addComponent(sexomedico, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(salariomedico, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nomemedico, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(unidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(bairro, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomemedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpfmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idademedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(sexomedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(salariomedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(celularmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(espmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novo)
                    .addComponent(salvar)
                    .addComponent(editar)
                    .addComponent(excluir)
                    .addComponent(cancelar)
                    .addComponent(pesquisar))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idmedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idmedicoActionPerformed

    private void emailmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailmedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailmedicoActionPerformed

    private void ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        limparCampos();
        idmedico.setEnabled(false);
        nomemedico.setEnabled(true);
        cpfmedico.setEnabled(true);
        idademedico.setEnabled(true);
        sexomedico.setEnabled(true);
        salariomedico.setEnabled(true);
        emailmedico.setEnabled(true);
        celularmedico.setEnabled(true);
        espmedico.setEnabled(true);
        rua.setEnabled(true);
        bairro.setEnabled(true);
        cep.setEnabled(true);
        unidade.setEnabled(true);
        novo.setEnabled(false);
        salvar.setEnabled(true);
        editar.setEnabled(false);
        excluir.setEnabled(false);
        cancelar.setEnabled(true);
        pesquisar.setEnabled(false);
    }//GEN-LAST:event_novoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        limparCampos();
        idmedico.setEnabled(true);
        nomemedico.setEnabled(false);
        cpfmedico.setEnabled(false);
        idademedico.setEnabled(false);
        sexomedico.setEnabled(false);
        salariomedico.setEnabled(false);
        emailmedico.setEnabled(false);
        celularmedico.setEnabled(false);
        espmedico.setEnabled(false);
        rua.setEnabled(false);
        bairro.setEnabled(false);
        cep.setEnabled(false);
        unidade.setEnabled(false);
        novo.setEnabled(true);
        salvar.setEnabled(false);
        editar.setEnabled(false);
        excluir.setEnabled(false);
        cancelar.setEnabled(false);
        pesquisar.setEnabled(true);
    }//GEN-LAST:event_cancelarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField celularmedico;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cpfmedico;
    private javax.swing.JButton editar;
    private javax.swing.JTextField emailmedico;
    private javax.swing.JTextField espmedico;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField idademedico;
    private javax.swing.JTextField idmedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomemedico;
    private javax.swing.JButton novo;
    private javax.swing.JButton pesquisar;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField salariomedico;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField sexomedico;
    private javax.swing.JTextField unidade;
    // End of variables declaration//GEN-END:variables

    public void limparCampos(){
        idmedico.setText("");
        nomemedico.setText("");
        cpfmedico.setText("");
        idademedico.setText("");
        sexomedico.setText("");
        salariomedico.setText("");
        emailmedico.setText("");
        celularmedico.setText("");
        espmedico.setText("");
        rua.setText("");
        bairro.setText("");
        cep.setText("");
        unidade.setText("");
    }

    public boolean validarCampos(){
        if (nomemedico.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo Nome: ");
            nomemedico.requestFocus();
            return false;           
        }

        if (cpfmedico.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo CPF! ");
            cpfmedico.requestFocus();
            return false;           
        }
        
        if (idademedico.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo Idade! ");
            idademedico.requestFocus();
            return false;           
        }    
        
        if (sexomedico.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo Sexo");
            sexomedico.requestFocus();
            return false;           
        }
       
        if (salariomedico.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo Salrio! ");
            salariomedico.requestFocus();
            return false;           
        }
        
        if (emailmedico.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo E-mail ");
            emailmedico.requestFocus();
            return false;           
        }
        
        if (celularmedico.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo Celular ");
            celularmedico.requestFocus();
            return false;           
        }
        
        if (espmedico.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo Especialidade ");
            espmedico.requestFocus();
            return false;           
        }
        
        if (rua.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo Rua ");
            rua.requestFocus();
            return false;           
        }
        
        if (bairro.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo Bairro ");
            bairro.requestFocus();
            return false;           
        }
        
        if (cep.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo CEP ");
            cep.requestFocus();
            return false;           
        }
        
        if (unidade.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo Unidade ");
            unidade.requestFocus();
            return false;           
        }
        return true;
        
    }
    
    public boolean preencherObjeto(){
        objMed = new medico();
        objMed.setNome(nomemedico.getText());
        objMed.setCpf(Integer.parseInt(cpfmedico.getText()));
        objMed.setIdade(Integer.parseInt(idademedico.getText()));
        objMed.setSexo(sexomedico.getText());
        objMed.setSalario(Float.parseFloat(salariomedico.getText()));
        objMed.setEmail(emailmedico.getText());
        objMed.setCelular(Integer.parseInt(celularmedico.getText()));
        objMed.setEspecialdade(espmedico.getText());
        objMed.setRua(rua.getText());
        objMed.setBairro(bairro.getText());
        objMed.setCep(Integer.parseInt(cep.getText()));
        objMed.setUnidade(unidade.getText());
        return true;
    }
    
}
